{ inputs, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix # generated by the installer (see README)

    # Hardware defaults from nixos-hardware
    inputs.nixos-hardware.nixosModules.common-cpu-intel
    inputs.nixos-hardware.nixosModules.common-pc-laptop
    inputs.nixos-hardware.nixosModules.common-pc-laptop-ssd

    # Our modular system config
    ../../modules/system/boot.nix
    ../../modules/system/networking.nix
    ../../modules/system/security.nix
    ../../modules/system/nix.nix
    ../../modules/system/desktop.nix
  ];

  networking.hostName = "lucas";

  # ---- User ----
  users.users.lucas = {
    isNormalUser = true;
    description = "Lucas";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" ];
    shell = pkgs.zsh;
  };
  # zsh must be enabled system-wide to be usable as a login shell.
  programs.zsh.enable = true;

  # ---- Locale & time (Stockholm) ----
  time.timeZone = "Europe/Stockholm";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_TIME = "sv_SE.UTF-8";
    LC_MONETARY = "sv_SE.UTF-8";
    LC_MEASUREMENT = "sv_SE.UTF-8";
    LC_NUMERIC = "sv_SE.UTF-8";
    LC_PAPER = "sv_SE.UTF-8";
  };
  # TTY keymap. Change to "sv-latin1" if your ThinkPad has a Swedish keyboard.
  console.keyMap = "sv-latin1";

  # ---- Intel UHD 620 (Kaby Lake-R, Gen9.5) ----
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver      # iHD VA-API driver (recommended for Gen9+)
      intel-compute-runtime   # OpenCL
    ];
  };
  # Force the modern iHD driver.
  environment.sessionVariables.LIBVA_DRIVER_NAME = "iHD";

  hardware.cpu.intel.updateMicrocode = true;

  # ---- zram swap (no disk swap, no hibernation) ----
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    # ~4 GB of compressed swap. Raise toward 100 if you hit memory pressure.
    memoryPercent = 50;
  };

  # Do not change after install — defines defaults at install time.
  system.stateVersion = "26.05";
}
